import {FormEvent,useEffect,useState} from 'react';
import {api} from '../lib/api';
import type {RelocationSite} from '../types';
import {PageHeader} from '../components/PageHeader';
import {Card} from '../components/Card';
import {DataTable} from '../components/DataTable';
import {FormField} from '../components/FormField';
import {Empty,ErrorBox} from '../components/Loading';
export default function CarryingCapacity(){const [sites,setSites]=useState<RelocationSite[]>([]);const [error,setError]=useState('');const [f,setF]=useState<any>({code:'',name:'',state:'',district:'',latitude:'',longitude:'',total_capacity:'',current_occupancy:'0'});const load=()=>api.get<RelocationSite[]>('/relocation/sites').then(setSites);useEffect(()=>{load()},[]);const submit=async(e:FormEvent)=>{e.preventDefault();try{await api.post('/relocation/sites',{...f,latitude:+f.latitude,longitude:+f.longitude,total_capacity:+f.total_capacity,current_occupancy:+f.current_occupancy,verified:false});await load()}catch(e:any){setError(e.message)}};return <><PageHeader title="Carrying Capacity Assessment" subtitle="Relocation sites use real stored capacity/infrastructure fields. Sites remain unverified until authority validation."/>{error&&<ErrorBox message={error}/>}<div className="grid-2 wide-left"><Card title="Candidate sites">{sites.length?<DataTable headers={['Site','District','Capacity','Occupied','Available','Future risk','Verified']}>{sites.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.district}</td><td>{s.total_capacity}</td><td>{s.current_occupancy}</td><td>{s.available_capacity}</td><td>{s.future_risk_score??'—'}</td><td>{s.verified?'Yes':'No'}</td></tr>)}</DataTable>:<Empty title="No relocation sites"/>}</Card><Card title="Add candidate site"><form className="form-grid compact" onSubmit={submit}>{Object.keys(f).map(k=><FormField label={k.replaceAll('_',' ')} key={k}><input required value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} type={['latitude','longitude','total_capacity','current_occupancy'].includes(k)?'number':'text'} step="any"/></FormField>)}<button className="btn primary">Add site</button><small>Verification is intentionally separate from creation.</small></form></Card></div></>}
