import {useEffect,useState} from 'react';
import {api} from '../lib/api';
import {Card,Stat} from '../components/Card';
import {ErrorBox,Loading} from '../components/Loading';
import {PageHeader} from '../components/PageHeader';
import {Link} from 'react-router-dom';

type Summary={habitations:number;latest_high_or_critical:number;active_sos:number;pending_citizen_reports:number;published_alerts:number;relocation_sites:number;verified_relocation_sites:number};
export default function Dashboard(){const [data,setData]=useState<Summary|null>(null);const [error,setError]=useState('');useEffect(()=>{api.get<Summary>('/dashboard/summary').then(setData).catch(e=>setError(e.message))},[]);return <><PageHeader title="Authority Dashboard" subtitle="Operational summary from the current database."/>{error&&<ErrorBox message={error}/>} {!data?<Loading/>:<div className="stat-grid"><Stat label="Habitations" value={data.habitations}/><Stat label="High/Critical assessments" value={data.latest_high_or_critical}/><Stat label="Active SOS" value={data.active_sos}/><Stat label="Pending citizen reports" value={data.pending_citizen_reports}/><Stat label="Published alerts" value={data.published_alerts}/><Stat label="Verified relocation sites" value={`${data.verified_relocation_sites}/${data.relocation_sites}`}/></div>}<div className="grid-2"><Card title="Primary planning workflow"><div className="workflow"><Link to="/risk-map">Risk Map</Link><span>→</span><Link to="/future-risk">Future Risk</Link><span>→</span><Link to="/relocation-priority">Priority</Link><span>→</span><Link to="/relocation-optimizer">Relocation</Link><span>→</span><Link to="/reports">Report</Link></div></Card><Card title="Data readiness"><p>The platform starts with no fictional operational records. Import or enter verified habitations, hazard observations, relocation sites and infrastructure data to enable analysis.</p><Link className="btn secondary" to="/habitation-analysis">Manage habitations</Link></Card></div></>}
