import {FormEvent,useState} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {VoiceSOS} from '../components/VoiceSOS';
import {api} from '../lib/api';
import {FormField} from '../components/FormField';
import {ErrorBox} from '../components/Loading';

export default function EmergencyLoginless(){
  const nav=useNavigate(); const state=useLocation().state as any;
  const [f,setF]=useState<any>({caller_name:'',phone:'',latitude:'',longitude:'',hazard_type:'',message:state?.transcript||'',transcript:state?.transcript||'',people_count:1,special_needs:[]});
  const [error,setError]=useState(''); const [sent,setSent]=useState<any>(null);
  const locate=()=>navigator.geolocation.getCurrentPosition(p=>setF({...f,latitude:p.coords.latitude,longitude:p.coords.longitude}),e=>setError(e.message),{enableHighAccuracy:true,timeout:10000});
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');try{const out=await api.post('/sos/public',{...f,latitude:+f.latitude,longitude:+f.longitude,hazard_type:f.hazard_type||null});setSent(out)}catch(e:any){setError(e.message)}};
  return <div className="public-emergency"><div className="public-emergency-card"><div className="brand"><div className="brand-mark">DM</div><div><b>Disaster Management</b><small>Emergency access</small></div></div><h1>Emergency SOS</h1><p>Share your current location and contact number with authorized responders. Do not enter false emergency requests.</p>{error&&<ErrorBox message={error}/>} {sent?<><div className="success-box"><b>SOS submitted</b><p>Reference: {sent.id}</p><p>Status: {sent.status}</p></div><button className="btn primary full" onClick={()=>nav('/login')}>Sign in to track</button></>:<form onSubmit={submit} className="form-grid"><FormField label="Your name"><input required value={f.caller_name} onChange={e=>setF({...f,caller_name:e.target.value})}/></FormField><FormField label="Phone number"><input required value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></FormField><button type="button" className="btn secondary" onClick={locate}>Capture current GPS</button><FormField label="Latitude"><input required type="number" step="any" value={f.latitude} onChange={e=>setF({...f,latitude:e.target.value})}/></FormField><FormField label="Longitude"><input required type="number" step="any" value={f.longitude} onChange={e=>setF({...f,longitude:e.target.value})}/></FormField><FormField label="Hazard"><select value={f.hazard_type} onChange={e=>setF({...f,hazard_type:e.target.value})}><option value="">Unknown</option><option>flood</option><option>landslide</option><option>cyclone</option><option>fire</option><option>other</option></select></FormField><VoiceSOS onTranscript={t=>setF({...f,transcript:t,message:f.message||t})}/><FormField label="Emergency message"><textarea value={f.message} onChange={e=>setF({...f,message:e.target.value})}/></FormField><button className="btn danger full">Send emergency SOS</button></form>}<button className="btn ghost full" onClick={()=>nav('/login')}>Back to login</button><small className="muted">Public SOS is rate-limited by phone number in this build. Production deployments should also add gateway/IP/device controls and phone verification policy.</small></div></div>
}
