import {FormEvent,useEffect,useState} from 'react';
import {api} from '../lib/api';
import type {FamilyGroup,FamilyMember} from '../types';
import {PageHeader} from '../components/PageHeader';
import {Card} from '../components/Card';
import {FormField} from '../components/FormField';
import {StatusBadge} from '../components/StatusBadge';
import {Empty} from '../components/Loading';
import {VoiceSOS} from '../components/VoiceSOS';

export default function FamilySafety(){
  const [rows,setRows]=useState<FamilyMember[]>([]); const [group,setGroup]=useState<FamilyGroup|null>(null); const [error,setError]=useState(''); const [voice,setVoice]=useState('');
  const [f,setF]=useState<any>({name:'',relationship:'',phone:'',age_group:'adult',location_sharing:false});
  const load=async()=>{try{const [contacts,g]=await Promise.all([api.get<FamilyMember[]>('/family'),api.get<FamilyGroup>('/family/portal/group')]);setRows(contacts);setGroup(g);}catch(e:any){setError(e.message||'Unable to load family safety')}};
  useEffect(()=>{load()},[]);
  const add=async(e:FormEvent)=>{e.preventDefault();setError('');try{await api.post('/family',{...f,special_assistance:[],sms_enabled:true,app_alerts_enabled:true});setF({...f,name:'',relationship:'',phone:''});await load();}catch(e:any){setError(e.message)}};
  const check=async(id:string,status:string)=>{await api.patch(`/family/${id}/check-in`,{safety_status:status});await load()};
  const myCheck=async(status:string,withLocation=true)=>{const send=(coords?:GeolocationCoordinates)=>api.patch<FamilyGroup>('/family/portal/check-in',{safety_status:status,location_sharing:withLocation,latitude:coords?.latitude,longitude:coords?.longitude}).then(setGroup).catch((e:any)=>setError(e.message));if(withLocation){navigator.geolocation.getCurrentPosition(p=>send(p.coords),e=>setError(e.message),{enableHighAccuracy:true,timeout:10000})}else send();};
  const voiceAction=(text:string)=>{setVoice(text);const t=text.toLowerCase();if(t.includes('safe')||t.includes('பாதுகாப்ப')) myCheck('safe');else if(t.includes('shelter')||t.includes('camp')||t.includes('முகாம்')) myCheck('at_shelter');else if(t.includes('help')||t.includes('danger')||t.includes('உதவி')||t.includes('ஆபத்து')) myCheck('need_help');};
  return <><PageHeader title="Family Safety" subtitle="Private family portal, emergency contacts, safety check-ins and consent-based location sharing."/>{error&&<div className="error-box">{error}</div>}
    <div className="grid-2"><Card title="Family Portal"><p>Share this private code only with trusted family members. They can create a Family Member account and join your family portal.</p>{group&&<><div className="family-code"><span>Family join code</span><strong>{group.join_code}</strong><button className="btn tiny" onClick={()=>navigator.clipboard?.writeText(group.join_code||'')}>Copy code</button></div><div className="button-row"><button className="btn primary" onClick={()=>myCheck('safe')}>✓ I’m Safe</button><button className="btn" onClick={()=>myCheck('at_shelter')}>At Shelter</button><button className="btn danger" onClick={()=>myCheck('need_help')}>Need Help</button></div><div className="voice-safety"><VoiceSOS label="🎙 Voice Safety Update" onTranscript={voiceAction}/>{voice&&<p className="transcript">Heard: <b>{voice}</b></p>}</div><div className="member-grid family-linked-list">{group.members.map(m=><div className="member-card" key={m.user_id}><div><b>{m.full_name}</b><small>{m.relationship} · {m.email}</small></div><StatusBadge value={m.safety_status}/><small>Location sharing: {m.location_sharing?'enabled':'off'}</small>{m.last_checkin_at&&<small>Last check-in: {new Date(m.last_checkin_at).toLocaleString()}</small>}</div>)}</div></>}</Card>
      <Card title="Add emergency contact"><form onSubmit={add} className="form-grid compact"><FormField label="Name"><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></FormField><FormField label="Relationship"><input required value={f.relationship} onChange={e=>setF({...f,relationship:e.target.value})}/></FormField><FormField label="Phone"><input required value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></FormField><FormField label="Age group"><select value={f.age_group} onChange={e=>setF({...f,age_group:e.target.value})}><option>child</option><option>adult</option><option>elderly</option></select></FormField><label className="check"><input type="checkbox" checked={f.location_sharing} onChange={e=>setF({...f,location_sharing:e.target.checked})}/> Enable location sharing with consent</label><button className="btn primary">Add contact</button></form></Card></div>
    <Card title="Emergency contact records">{rows.length?<div className="member-grid">{rows.map(m=><div className="member-card" key={m.id}><div><b>{m.name}</b><small>{m.relationship} · {m.phone}</small></div><StatusBadge value={m.safety_status}/><div className="button-row"><button className="btn tiny" onClick={()=>check(m.id,'safe')}>Safe</button><button className="btn tiny ghost" onClick={()=>check(m.id,'need_help')}>Need help</button><button className="btn tiny ghost" onClick={()=>check(m.id,'at_shelter')}>At shelter</button></div><small>Location sharing: {m.location_sharing?'enabled':'off'}</small></div>)}</div>:<Empty title="No emergency contacts"/>}</Card>
  </>
}
