import {FormEvent,useEffect,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {api,ApiError} from '../lib/api';
import {PageHeader} from '../components/PageHeader';
import {Card} from '../components/Card';
import {StatusBadge} from '../components/StatusBadge';
import {VoiceSOS} from '../components/VoiceSOS';
import type {FamilyGroup} from '../types';

export default function FamilyPortal(){
  const nav=useNavigate(); const [group,setGroup]=useState<FamilyGroup|null>(null); const [needsJoin,setNeedsJoin]=useState(false); const [joinCode,setJoinCode]=useState(''); const [relationship,setRelationship]=useState('Family member'); const [error,setError]=useState(''); const [voiceText,setVoiceText]=useState('');
  const load=async()=>{setError('');try{setGroup(await api.get<FamilyGroup>('/family/portal/group'));setNeedsJoin(false);}catch(e:any){if(e instanceof ApiError&&e.status===404){setNeedsJoin(true);setGroup(null);}else setError(e.message||'Unable to load family portal')}};
  useEffect(()=>{load()},[]);
  const join=async(e:FormEvent)=>{e.preventDefault();setError('');try{setGroup(await api.post<FamilyGroup>('/family/portal/join',{join_code:joinCode,relationship}));setNeedsJoin(false);}catch(e:any){setError(e.message||'Unable to join family')}};
  const update=async(status:string,withLocation=false)=>{setError('');const send=(coords?:GeolocationCoordinates)=>api.patch<FamilyGroup>('/family/portal/check-in',{safety_status:status,location_sharing:withLocation,latitude:coords?.latitude,longitude:coords?.longitude}).then(setGroup).catch((e:any)=>setError(e.message));if(withLocation){navigator.geolocation.getCurrentPosition(p=>send(p.coords),e=>setError(e.message),{enableHighAccuracy:true,timeout:10000})}else send()};
  const voiceAction=(text:string)=>{setVoiceText(text);const t=text.toLowerCase();if(t.includes('safe')||t.includes('நான் பாதுகாப்பாக')||t.includes('பாதுகாப்பாக இருக்கிறேன்')) update('safe',true);else if(t.includes('shelter')||t.includes('camp')||t.includes('முகாம்')) update('at_shelter',true);else if(t.includes('help')||t.includes('danger')||t.includes('உதவி')||t.includes('ஆபத்து')) update('need_help',true);};
  return <><PageHeader title="Family Portal" subtitle="Private family-group check-ins, consent-based location sharing and emergency voice access."/>{error&&<div className="error-box">{error}</div>}
    {needsJoin?<Card title="Join your family"><p>Your Family Member account is active. Ask the Citizen account owner for the private 8-character family code.</p><form className="inline-form" onSubmit={join}><label className="field"><span>Family join code</span><input required maxLength={12} value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="ABCD2345"/></label><label className="field"><span>Relationship</span><input required value={relationship} onChange={e=>setRelationship(e.target.value)} placeholder="Mother / Brother / Spouse"/></label><button className="btn primary">Join family</button></form></Card>:group&&<>
      <div className="stat-grid"><div className="stat"><span>Family</span><strong>{group.name}</strong><small>{group.members.length} linked accounts</small></div><div className="stat"><span>Safe</span><strong>{group.members.filter(m=>m.safety_status==='safe').length}</strong><small>latest check-ins</small></div><div className="stat"><span>Need help</span><strong>{group.members.filter(m=>m.safety_status==='need_help').length}</strong><small>requires attention</small></div><div className="stat"><span>At shelter</span><strong>{group.members.filter(m=>m.safety_status==='at_shelter').length}</strong><small>checked in</small></div></div>
      <div className="grid-2"><Card title="My safety check-in"><div className="family-action-grid"><button className="btn primary" onClick={()=>update('safe',true)}>✓ I’m Safe + Share Location</button><button className="btn" onClick={()=>update('at_shelter',true)}>🏠 I’m at Shelter</button><button className="btn danger" onClick={()=>update('need_help',true)}>⚠ I Need Help</button><button className="btn danger" onClick={()=>nav('/sos')}>🆘 Open SOS</button></div><div className="voice-safety"><VoiceSOS label="🎙 Voice Safety Update" language="en-IN" onTranscript={voiceAction}/>{voiceText&&<p className="transcript">Heard: <b>{voiceText}</b></p>}<small className="muted">Try: “I am safe”, “I need help”, or “I am at shelter”. Tamil emergency phrases are also recognized when supported by the browser.</small></div></Card>
      <Card title="Family members"><div className="member-grid">{group.members.map(m=><div className="member-card" key={m.user_id}><div><b>{m.full_name}</b><small>{m.relationship} · {m.email}</small></div><StatusBadge value={m.safety_status}/><small>Location sharing: {m.location_sharing?'enabled':'off'}</small>{m.last_checkin_at&&<small>Last check-in: {new Date(m.last_checkin_at).toLocaleString()}</small>}{m.location_sharing&&m.last_latitude!=null&&<small>Last location: {m.last_latitude.toFixed(5)}, {m.last_longitude?.toFixed(5)}</small>}</div>)}</div></Card></div>
    </>}
  </>
}
