import {FormEvent,useEffect,useState} from 'react';
import {api} from '../lib/api';
import type {Habitation} from '../types';
import {PageHeader} from '../components/PageHeader';
import {Card} from '../components/Card';
import {DataTable} from '../components/DataTable';
import {FormField} from '../components/FormField';
import {ErrorBox,Empty} from '../components/Loading';
type Candidate={site_id:string;site_name:string;distance_km:number;available_capacity:number;capacity_sufficient:boolean;future_risk_score:number|null;infrastructure_score:number|null;overall_score:number;rationale:any};
export default function RelocationOptimizer(){const [hs,setHs]=useState<Habitation[]>([]);const [hid,setHid]=useState('');const [population,setPopulation]=useState(0);const [rows,setRows]=useState<Candidate[]>([]);const [error,setError]=useState('');useEffect(()=>{api.get<Habitation[]>('/habitations').then(x=>{setHs(x);if(x[0]){setHid(x[0].id);setPopulation(x[0].population)}})},[]);const change=(id:string)=>{setHid(id);const h=hs.find(x=>x.id===id);if(h)setPopulation(h.population)};const run=async(e:FormEvent)=>{e.preventDefault();setError('');try{setRows(await api.post<Candidate[]>(`/relocation/recommend/${hid}`,{population_to_relocate:population,weights:{capacity:.28,future_safety:.28,infrastructure:.24,distance:.20}}))}catch(e:any){setError(e.message)}};return <><PageHeader title="Smart Relocation Optimizer" subtitle="Ranks verified candidate sites by explicit capacity, future-safety, infrastructure and distance weights."/><Card><form onSubmit={run} className="inline-form"><FormField label="Source habitation"><select value={hid} onChange={e=>change(e.target.value)}>{hs.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></FormField><FormField label="Population to relocate"><input type="number" min={1} value={population} onChange={e=>setPopulation(+e.target.value)}/></FormField><button className="btn primary">Rank sites</button></form>{error&&<ErrorBox message={error}/>}</Card><Card title="Ranked candidates">{rows.length?<DataTable headers={['Rank','Site','Distance','Available capacity','Capacity','Future risk','Infrastructure','Overall']}>{rows.map((r,i)=><tr key={r.site_id}><td>{i+1}</td><td>{r.site_name}</td><td>{r.distance_km} km</td><td>{r.available_capacity}</td><td>{r.capacity_sufficient?'Sufficient':'Insufficient'}</td><td>{r.future_risk_score??'Unknown'}</td><td>{r.infrastructure_score??'Unknown'}</td><td><b>{r.overall_score}</b></td></tr>)}</DataTable>:<Empty title="No recommendation yet" description="Only verified relocation sites are ranked."/>}</Card></>}
