import {FormEvent,useEffect,useState} from 'react';
import {api} from '../lib/api';
import {PageHeader} from '../components/PageHeader';
import {Card} from '../components/Card';
import {DataTable} from '../components/DataTable';
import {FormField} from '../components/FormField';
import {StatusBadge} from '../components/StatusBadge';
import {Empty} from '../components/Loading';
export default function Reports(){const [rows,setRows]=useState<any[]>([]);const [f,setF]=useState({report_type:'decision_support',title:'',scope:'{}',content:'{}'});const load=()=>api.get<any[]>('/reports').then(setRows);useEffect(()=>{load()},[]);const submit=async(e:FormEvent)=>{e.preventDefault();await api.post('/reports',{report_type:f.report_type,title:f.title,scope:JSON.parse(f.scope),content:JSON.parse(f.content)});await load()};const openPdf=async(id:string)=>{const token=localStorage.getItem('dm_token');const res=await fetch(`${api.baseUrl}/reports/${id}/pdf`,{headers:{Authorization:`Bearer ${token}`}});const blob=await res.blob();const url=URL.createObjectURL(blob);window.open(url,'_blank')};return <><PageHeader title="Reports & Recommendations" subtitle="Persist decision-support reports and export PDF with the current reviewed content."/><div className="grid-2"><Card title="Generate report"><form onSubmit={submit} className="form-grid"><FormField label="Type"><input value={f.report_type} onChange={e=>setF({...f,report_type:e.target.value})}/></FormField><FormField label="Title"><input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></FormField><FormField label="Scope JSON"><textarea value={f.scope} onChange={e=>setF({...f,scope:e.target.value})}/></FormField><FormField label="Content JSON"><textarea value={f.content} onChange={e=>setF({...f,content:e.target.value})}/></FormField><button className="btn primary">Save report</button></form></Card><Card title="Report history">{rows.length?<DataTable headers={['Title','Type','Status','Created','']}>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.report_type}</td><td><StatusBadge value={r.status}/></td><td>{new Date(r.created_at).toLocaleString()}</td><td><button className="btn tiny" onClick={()=>openPdf(r.id)}>PDF</button></td></tr>)}</DataTable>:<Empty title="No reports"/>}</Card></div></>}
