import {FormEvent,useEffect,useState} from 'react';
import {api} from '../lib/api';
import {PageHeader} from '../components/PageHeader';
import {Card} from '../components/Card';
import {DataTable} from '../components/DataTable';
import {FormField} from '../components/FormField';
import {Empty,ErrorBox} from '../components/Loading';
import {StatusBadge} from '../components/StatusBadge';
export default function SatelliteAnalysis(){const [rows,setRows]=useState<any[]>([]);const [error,setError]=useState('');const [f,setF]=useState<any>({name:'',change_type:'land_use_change',start_date:'',end_date:'',data_source:'',source_url:''});const load=()=>api.get<any[]>('/satellite/changes').then(setRows);useEffect(()=>{load()},[]);const submit=async(e:FormEvent)=>{e.preventDefault();try{await api.post('/satellite/changes',{...f,start_date:new Date(f.start_date).toISOString(),end_date:new Date(f.end_date).toISOString(),metrics:{}});await load()}catch(e:any){setError(e.message)}};return <><PageHeader title="Satellite Change Detection" subtitle="Register real external/processed change products and track verification. The platform does not fabricate satellite observations."/>{error&&<ErrorBox message={error}/>}<div className="grid-2"><Card title="Add change product"><form className="form-grid compact" onSubmit={submit}><FormField label="Name"><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></FormField><FormField label="Change type"><input required value={f.change_type} onChange={e=>setF({...f,change_type:e.target.value})}/></FormField><FormField label="Start"><input required type="datetime-local" value={f.start_date} onChange={e=>setF({...f,start_date:e.target.value})}/></FormField><FormField label="End"><input required type="datetime-local" value={f.end_date} onChange={e=>setF({...f,end_date:e.target.value})}/></FormField><FormField label="Data source"><input required placeholder="Sentinel-2 / uploaded analysis / other" value={f.data_source} onChange={e=>setF({...f,data_source:e.target.value})}/></FormField><FormField label="Source URL"><input value={f.source_url} onChange={e=>setF({...f,source_url:e.target.value})}/></FormField><button className="btn primary">Register product</button></form></Card><Card title="Change records">{rows.length?<DataTable headers={['Name','Type','Source','Status','Period']}>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.change_type}</td><td>{r.data_source}</td><td><StatusBadge value={r.status}/></td><td>{new Date(r.start_date).toLocaleDateString()} → {new Date(r.end_date).toLocaleDateString()}</td></tr>)}</DataTable>:<Empty title="No satellite/change products"/>}</Card></div></>}
